### ISSUE TITLE
connectTo Method it's crashing 

### ISSUE THREAD

**Issue by wellmonge** [blackdeve/react-native-wifi#1]
At line 283 theres a peace of code, I'm getting this error when I trying to connect to WIFI- WPA/WPA2 PSK:

`283 - boolean enableNetwork = wifi.enableNetwork(updateNetwork, true);`
`284	-	if ( !enableNetwork ) {`
`285	-		return false;`
`286 -		};`

ENVIROMENT:
RN: 0.54.0
react-native-wifi: 1.0.1
node: 8.9.1
npm: 5.6.0

Digging on Android developers documentation I found this...

![image](https://user-images.githubusercontent.com/5003655/38517036-ad568798-3c06-11e8-9413-c531e24707fe.png)

**Comment by pstanton** [comment]
works for me on android (if wifi is enabled first), however crashes every time on iOS. the network is connected to, however my app crashes.
