### ISSUE TITLE
getCurrentWifiSSID does not work in my project

### ISSUE THREAD

**Issue by jpdarveau** [blackdeve/react-native-wifi#11]
I'm a newbie with react native and I am trying to use react-native-wifi in my app but nothing is working for me. 

I am probably missing something stupid, but like I said I am learning react-native.

So, I npm installed react-native-wifi to my project and linked it
imported WifiManager into my component

I linked a function to a button to call WifiManager.getCurrentWifiSSID() as a test.

That is where i'm blocked... when I tap my button I'm getting an error message : "undefined is not a an object (evaluating '_reactNativeWifi2.default.getCurrentWifiSSID')

What I'm I missing?

Here are my dependencies from package.json
`"dependencies": {
    "expo": "^30.0.1",
    "native-base": "^2.8.1",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
    "react-native-wifi": "^1.0.1",
    "react-navigation": "^2.18.0"
  }`

**Comment by ferlopezm94** [comment]
+1

**Comment by wangjoshuah** [comment]
@jpdarveau how did you resolve this?
