### ISSUE TITLE
loadWifiList for iOS

### ISSUE THREAD

**Issue by henrymcl** [blackdeve/react-native-wifi#31]
This is on overall very nice package, especially with the loadWifiList method :D
Could you please create the method loadWifiList for iOS for consistency?

**Comment by ashryOlarm** [comment]
@henry132109 
There is no native public API for IOS to do that.

**Comment by henrymcl** [comment]
> @henry132109
> There is no native public API for IOS to do that.

Thank you for that information! I shall close this now.
